### ISSUE TITLE
Electron won't start

### ISSUE THREAD

**Issue by bartusek27** [ags131/screeps-client#1]
Hi, I got this error when I try to start Electron on my PS:
```
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle screeps-web-client@1.0.0~prestart: screeps-web-client@1.0.0
6 silly lifecycle screeps-web-client@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle screeps-web-client@1.0.0~start: screeps-web-client@1.0.0
8 verbose lifecycle screeps-web-client@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle screeps-web-client@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/app/screeps-client/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle screeps-web-client@1.0.0~start: CWD: /app/screeps-client
11 silly lifecycle screeps-web-client@1.0.0~start: Args: [ '-c', 'electron src/electron' ]
12 silly lifecycle screeps-web-client@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle screeps-web-client@1.0.0~start: Failed to exec start script
14 verbose stack Error: screeps-web-client@1.0.0 start: `electron src/electron`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid screeps-web-client@1.0.0
16 verbose cwd /app/screeps-client
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error screeps-web-client@1.0.0 start: `electron src/electron`
22 error Exit status 1
23 error Failed at the screeps-web-client@1.0.0 start script 'electron src/electron'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the screeps-web-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron src/electron
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs screeps-web-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls screeps-web-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by AlinaNova21** [comment]
You may need to do `npm install -g electron` first
