### ISSUE TITLE
Cannot load /screeps-web-client/index.js

### ISSUE THREAD

**Issue by OGbtraven** [ags131/screeps-client#2]
I installed this on my private server but it doesn't want to run. When attempting to run engine_runner(s), engine_proccessor(s), engine_main, and backend all erratically restart with the following looping in engine_main.log & backend.log:

Loading mods from "/home/bt/mods.json"
 - /home/bt/node_modules/screepsmod-pure-automation/index.js
 - /home/bt/node_modules/screepsmod-auth/index.js
Cannot load "/home/bt/node_modules/screeps-web-client/index.js": module.exports is not a function!
Connecting to storage
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/home/bt/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/bt/node_modules/screeps-web-client/index.js:24:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by ags131** [comment]
It should point to mod.js rather than index.js, also, keep in mind it doesn't have auth UI added yet, so login is still hardcoded.

**Comment by OGbtraven** [comment]
Oops, that's a bit embarrassing. Thanks! 

I put my info in the auth.js, I just thought it would be cool to check on my private server from my phone. Maybe I can help you implement some stuff once I learn the ropes though :)
